version: "3.7"

services:

  application:
    restart: unless-stopped
    tty: true
    build:
      context: ./
      args:
        user: ignashkins
        uid: 9999
      dockerfile: docker/php/Dockerfile
    image: laravel
    container_name: laravel-app
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
    networks:
      - laravel

  database:
    restart: unless-stopped
    container_name: laravel-mysql
    image: mysql:5.7
    networks:
      - laravel
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql

  nginx:
    restart: unless-stopped
    tty: true
    container_name: laravel-nginx
    image: nginx:1.19-alpine
    ports:
      - 2000:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      - laravel

  gearman:
    restart: unless-stopped
    container_name: gearman
    build:
      context: ./
      dockerfile: docker/gearman/Dockerfile
    image: gearman
    ports:
      - 4730:4730
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
