version: "3.7"

services:

  application:
    build:
      args:
        user: ignashkins
        uid: 9999
      context: ./
      dockerfile: Dockerfile
    image: laravel
    container_name: laravel-app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - laravel

  database:
    container_name: laravel-mysql
    image: mysql:5.7
    networks:
      - laravel
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql

  nginx:
    container_name: laravel-nginx
    image: nginx:1.19-alpine
    ports:
      - 2000:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
